### ISSUE TITLE
how to install?

### ISSUE THREAD

**Issue by unnir** [ucb-art/laygo#1]
Hi,

please add a build option for python, something like:

`python build.py install `

because I can't import the laygo.

`ModuleNotFoundError: No module named 'laygo'`

btw, pip option would work too.

**Comment by jdhan** [comment]
Thanks for your suggestion! Currently, the package is being developed and tested. Once we have a stable version with full documentation, we are going to make a pip setup for installation. In the mean time, please use **git clone git@github.com:ucb-art/laygo.git** to install the package in your working directory (and let your PYTHONPATH to include your working directory)
